[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]
